channels:
- conda-forge
dependencies:
- python=3.11.13
- pip<=24.0
- pip:
  - mlflow==2.12.1
  - catboost==1.2.8
  - ipywidgets==8.1.7
  - numpy==1.26.4
  - pandas==2.3.2
  - psutil==7.1.0
  - pyarrow==15.0.2
  - scikit-learn==1.7.2
  - scipy==1.16.2
  - xgboost==2.1.4
name: mlflow-env
