name: Predict on new data or with new model

on: 
  push:
    branches:
      - test2
    paths:  
      - 'data/raw/test.csv'
      - 'data/processed/test.csv'
      - 'ARISA_DSML/predict.py'
      - 'models/catboost_model.cbm'
  workflow_dispatch:  

jobs:
  preprocess:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with: 
          python-version: "3.11"

      - name: Install dependencies
        run: make requirements

      - name: Configure Kaggle
        run: |
          mkdir -p $HOME/.config/kaggle
          echo "{\"username\":\"${{ secrets.KAGGLE_USERNAME }}\",\"key\":\"${{ secrets.KAGGLE_KEY }}\"}" > $HOME/.config/kaggle/kaggle.json
          chmod 600 $HOME/.config/kaggle/kaggle.json

      - name: Run preprocessing
        run: make preprocess

      - name: Upload preprocessed data
        uses: actions/upload-artifact@v4
        with:
          name: processed-data
          path: data/processed

  predict:
    runs-on: ubuntu-latest
    needs: preprocess
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download processed data
        uses: actions/download-artifact@v4
        with:
          name: processed-data
          path: data/processed

      - name: Set up Python
        uses: actions/setup-python@v4
        with: 
          python-version: "3.11"

      - name: Install dependencies
        run: make requirements

      - name: Start MLflow tracking server
        run: |
          nohup mlflow server \
            --backend-store-uri sqlite:///mlflow.db \
            --default-artifact-root file:./mlruns \
            --host 0.0.0.0 \
            --port 5000 > mlflow.log 2>&1 &
          sleep 5

      - name: Train model
        env:
          MLFLOW_TRACKING_URI: "http://localhost:5000"
        run: make train

      - name: Resolve champion/challenger
        env:
          MLFLOW_TRACKING_URI: "http://localhost:5000"
        run: make resolve

      - name: Predict on test data
        env:
          MLFLOW_TRACKING_URI: "http://localhost:5000"
        run: make predict

      - name: Upload predictions
        uses: actions/upload-artifact@v4
        with:
          name: predictions
          path: models/preds.csv
