name: Predict on new data or with new model

on:
  workflow_dispatch:   # uruchamianie ręczne z Actions

jobs:
  predict:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run prediction
        run: python ARISA_DSML/predict.py
